### ISSUE TITLE
regression due to user interest filter

### ISSUE THREAD

**Issue by louking** [louking/members#10]
regressed in https://github.com/louking/members/commit/d061f9568179e1bcd03d94f8901b9370f1943517

```
Traceback (most recent call last):
  File "C:\Users\lking\Documents\Lou's Software\projects\loutilities\loutilities\loutilities\tables.py", line 559, in wrapped_f
    f(self,*args, **kwargs)
  File "C:\Users\lking\Documents\Lou's Software\projects\loutilities\loutilities\loutilities\tables.py", line 1032, in put
    thisrow = self.updaterow(thisid, thisdata)
  File "C:\Users\lking\Documents\Lou's Software\projects\loutilities\loutilities\loutilities\tables.py", line 2407, in updaterow
    self.dte.set_dbrow(formdata, dbrow)
  File "C:\Users\lking\Documents\Lou's Software\projects\loutilities\loutilities\loutilities\tables.py", line 294, in set_dbrow
    setattr(dbrow, dbattr, callback(inrow))
  File "C:\Users\lking\Documents\Lou's Software\projects\loutilities\loutilities\loutilities\tables.py", line 1411, in set
    thisitem = self.viamodel.query.filter_by(**queryfilter).one()
  File "C:\Users\lking\Documents\Lou's Software\projects\members\members\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3350, in one
    "Multiple rows were found for one()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
```

**Comment by louking** [comment]
also https://github.com/louking/loutilities/commit/5d28e2c81bf4acfea19ce1a04d5295b7de3211a2
