### ISSUE TITLE
BuildError: Could not build url for endpoint '_uploads.uploaded_file' with values ['filename', 'setname']

### ISSUE THREAD

**Issue by louking** [louking/members#529]
When upload of picture to newsletter item, the following exception is seen.

```
Message type:       ERROR
Location:           /var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1449
Module:             app
Function:           log_exception
Time:               2022-11-10 09:03:10,751
User:               xxxxx

Message:

Exception on /admin/uploads [POST]

Traceback (most recent call last):
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/uploads.py", line 27, in post
    'url': url_for('_uploads.uploaded_file', setname='images', filename=filename, _external=True)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '_uploads.uploaded_file' with values ['filename', 'setname']. Did you mean 'admin.uploads' instead?
```

**Comment by louking** [comment]
flask-reuploaded 1.0+ required `UPLOADS_AUTOSERVE: True` configuration. See https://flask-reuploaded.readthedocs.io/en/latest/configuration/?highlight=_uploads#autoserve-configuration
