### ISSUE TITLE
racing team application: missing date is allowed

### ISSUE THREAD

**Issue by louking** [louking/members#571]
```
Name	Johanna *******
Email	*********
Birth Date	199*-**-**
Gender	F
Race 1 - Name	Krumpe's Donut Alley Rally 5k
Race 1 - Location	Hagerstown, MD
Race 1 - Date	
Race 1 - Age	
Race 1 - Distance	5
km
road
Race 1 - Official Time (hh:mm:ss)	00:20:49
Race 1 - Results Website	https://runsignup.com/Race/Results/71107/IndividualResult/sBxt?resultSetId=397072#U56006091
Race 1 - Age Grade	(based on birth date, gender, race date, distance, surface, time)
```

**Comment by louking** [comment]
This also causes exception when loading Racing Team Applications view:

```
Message type:       ERROR
Location:           /var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1449](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1449)
Module:             app
Function:           log_exception
Time:               2023-12-10 18:04:40,191
User:               Heidi

Message:

Exception on /admin/fsrc/rt_applns [GET]

Traceback (most recent call last):
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py)", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask_security/decorators.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask_security/decorators.py)", line 394, in decorated_view
    return fn(*args, **kwargs)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py)", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py)", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 2807, in get
    return super(DbCrudApi, self).get()
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 1263, in get
    return self._renderpage()
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py)", line 991, in _renderpage
    thisentry = self.nexttablerow()
  File "/var/www/[www.members.loutilities.com/members/members/members/views/admin/racingteam_admin.py](http://www.members.loutilities.com/members/members/members/views/admin/racingteam_admin.py)", line 440, in nexttablerow
    results = SortedKeyList(dbrec.rt_results, key=lambda a: a.eventdate)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/sortedcontainers/sortedlist.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/sortedcontainers/sortedlist.py)", line 1750, in __init__
    self._update(iterable)
  File "/var/www/[www.members.loutilities.com/venv/lib/python3.9/site-packages/sortedcontainers/sortedlist.py](http://www.members.loutilities.com/venv/lib/python3.9/site-packages/sortedcontainers/sortedlist.py)", line 1878, in update
    values = sorted(iterable, key=self._key)
TypeError: '<' not supported between instances of 'datetime.date' and 'NoneType'****
```
