### ISSUE TITLE
exception: "invalid URL: can't find meeting" when inviting people for newsletter input

### ISSUE THREAD

**Issue by louking** [louking/members#572]
```
Message type:       ERROR
Location:           /var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1449
Module:             app
Function:           log_exception
Time:               2023-12-08 08:10:44,445
User:               anonymous

Message:

Exception on /admin/fsrc/memberstatusreport [GET]

Traceback (most recent call last):
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)  # type: ignore
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/meetings_common.py", line 491, in __init__
    super().__init__(**args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/user/tables.py", line 46, in __init__
    super().__init__(**args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 3130, in __init__
    super(DbCrudApiRolePermissions, self).__init__(**args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 2574, in __init__
    super(DbCrudApi, self).__init__(**args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 925, in __init__
    childrowoptions = self.childrowoptions() if callable(self.childrowoptions) else self.childrowoptions
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/meetings_common.py", line 375, in memberstatusreport_childrowoptions
    raise ParameterError('invalid URL: can\'t find meeting')
members.views.admin.meetings_common.ParameterError: invalid URL: can't find meeting
```

**Comment by louking** [comment]
dup #724
