### ISSUE TITLE
taskdetails exception on .one() call

### ISSUE THREAD

**Issue by louking** [louking/members#586]
```
Message type:       ERROR
Location:           /var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py:1744
Module:             app
Function:           log_exception
Time:               2024-01-14 14:41:40,550
User:               **********************

Message:

Exception on /admin/fsrc/taskdetails [GET]

Traceback (most recent call last):
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask_security/decorators.py", line 394, in decorated_view
    return fn(*args, **kwargs)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 2810, in get
    return super(DbCrudApi, self).get()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 1264, in get
    return self._renderpage()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 992, in _renderpage
    thisentry = self.nexttablerow()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 2899, in nexttablerow
    return self.dte.get_response_data(dbrecord)
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/loutilities/tables.py", line 370, in get_response_data
    data[key] = callback(dbentry)
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/leadership_tasks_admin.py", line 553, in <lambda>
    formmapping['lastcompleted'] = lambda tu: lastcompleted(tu.task, tu.member)
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/viewhelpers.py", line 123, in lastcompleted
    taskcompletion = get_task_completion(task, user)
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/viewhelpers.py", line 100, in get_task_completion
    localuser = user2localuser(user)
  File "/var/www/www.members.loutilities.com/members/members/members/views/admin/viewhelpers.py", line 119, in user2localuser
    return LocalUser.query.filter_by(user_id=user.id, interest=localinterest).one()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2865, in one
    return self._iter().one()
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1417, in one
    return self._only_one_row(
  File "/var/www/www.members.loutilities.com/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 614, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
```

**Comment by louking** [comment]
deleted errant Kathy Cxx and Chris Dxx localuser records
