### ISSUE TITLE
missing User referenced from LocalUser (9/30/24 database backups)

### ISSUE THREAD

**Issue by louking** [louking/members#601]
```
2024-11-06 14:29:47 [2024-11-06 19:29:47 +0000] [21] [ERROR] Error handling request /admin/fsrc/taskdetails?interest=fsrc
2024-11-06 14:29:47 Traceback (most recent call last):
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle
2024-11-06 14:29:47     self.handle_request(listener, req, client, addr)
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
2024-11-06 14:29:47     respiter = self.wsgi(environ, resp.start_response)
2024-11-06 14:29:47                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
2024-11-06 14:29:47     return self.wsgi_app(environ, start_response)
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 183, in __call__
2024-11-06 14:29:47     return self.app(environ, start_response)
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
2024-11-06 14:29:47     response = self.handle_exception(e)
2024-11-06 14:29:47                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-11-06 14:29:47     response = self.full_dispatch_request()
2024-11-06 14:29:47                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
2024-11-06 14:29:47     rv = self.handle_user_exception(e)
2024-11-06 14:29:47          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
2024-11-06 14:29:47     rv = self.dispatch_request()
2024-11-06 14:29:47          ^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
2024-11-06 14:29:47     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask_security/decorators.py", line 429, in decorated_view
2024-11-06 14:29:47     return current_app.ensure_sync(fn)(*args, **kwargs)
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/views.py", line 110, in view
2024-11-06 14:29:47     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/flask/views.py", line 191, in dispatch_request
2024-11-06 14:29:47     return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/loutilities/tables.py", line 2817, in get
2024-11-06 14:29:47     return super(DbCrudApi, self).get()
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/loutilities/tables.py", line 1266, in get
2024-11-06 14:29:47     return self._renderpage()
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/loutilities/tables.py", line 989, in _renderpage
2024-11-06 14:29:47     self.open()
2024-11-06 14:29:47   File "/app/members/views/admin/leadership_tasks_admin.py", line 585, in open
2024-11-06 14:29:47     localusers = [lu for lu in localusersdb if has_oneof_roles(localuser2user(lu), TASK_CHECKLIST_ROLES_ACCEPTED)]
2024-11-06 14:29:47                                                                ^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/app/members/views/admin/viewhelpers.py", line 112, in localuser2user
2024-11-06 14:29:47     return User.query.filter_by(id=localuser.user_id).one()
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2865, in one
2024-11-06 14:29:47     return self._iter().one()
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1417, in one
2024-11-06 14:29:47     return self._only_one_row(
2024-11-06 14:29:47            ^^^^^^^^^^^^^^^^^^^
2024-11-06 14:29:47   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
2024-11-06 14:29:47     raise exc.NoResultFound(
2024-11-06 14:29:47 sqlalchemy.exc.NoResultFound: No row was found when one was required
```

**Comment by louking** [comment]
Issue was that members database was newer than user's database and there were extra entries. This was a development environment issue only
